server:
  port: 8761

spring:
  application:
    name: discovery-service


eureka:
  client:
    enable: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  registration:
    enabled: false